# Generated by Django 2.2.10 on 2020-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200527_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('open', 'OPEN'), ('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED')], default='created', max_length=6),
        ),
    ]
