# Generated by Django 2.2.10 on 2020-05-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200528_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ref_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
