# Generated by Django 2.2.10 on 2020-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200528_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
