# Generated by Django 2.2.10 on 2020-06-02 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofileinfo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2),
        ),
    ]
