# Generated by Django 2.2.10 on 2020-06-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200602_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TimeOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mins', models.IntegerField()),
                ('ref_id', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('open', 'OPEN'), ('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED')], default='created', max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
