# Generated by Django 2.2.10 on 2020-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200603_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeonline',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='timeonline',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='timeonline',
            name='status',
        ),
        migrations.AddField(
            model_name='timeonline',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeonline',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
