# Generated by Django 2.2.13 on 2020-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200603_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('open', 'OPEN'), ('pending', 'PENDING'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED')], default='created', max_length=10),
        ),
    ]
