# Generated by Django 2.2.10 on 2020-08-10 15:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200610_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6),
        ),
    ]
