# Generated by Django 2.2.10 on 2020-05-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tutor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfid', models.CharField(max_length=100)),
                ('qid', models.CharField(max_length=100)),
                ('aid', models.CharField(max_length=100)),
                ('tutor_id', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=5)),
                ('remarks', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('attachment', models.ImageField(default=False, upload_to=tutor.models.user_directory_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
