# Generated by Django 2.2.10 on 2020-05-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorfeedback',
            name='tfid',
        ),
    ]
