# Generated by Django 2.2.10 on 2020-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_remove_tutorfeedback_tfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorfeedback',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
