# Generated by Django 2.2.10 on 2020-05-26 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('qtitle', models.CharField(max_length=100)),
                ('view_status', models.CharField(max_length=2)),
                ('view_mode', models.CharField(max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
                ('remarks', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('view_status', models.CharField(default='0', max_length=2)),
                ('attachment', models.FileField(default=False, upload_to='questions/')),
                ('accepted_by', models.CharField(max_length=100)),
                ('question_type', models.CharField(default='0', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
