# Generated by Django 2.2.10 on 2020-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
