# Generated by Django 2.2.13 on 2020-06-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutee', '0002_question_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='accepted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
